
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Dec 21 18:50:36 CET 2011
//----------------------------------------------------

package compiler.parsers;

/** CUP generated class containing symbol constants. */
public class symboltable.Symbols {
  /* terminals */
  public static final int error = 1;
  public static final int ANY = 2;
  public static final int EOF = 0;
}

