/* The following code was generated by JFlex 1.4.3 on 23.11.11 00:25 */

package ptc.nase.frontend;

import ptc.nase.SymbolTable;
import java.io.IOException;
import java.io.FileNotFoundException;
import java.io.FileReader;
import ptc.nase.Nase;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 23.11.11 00:25 from the specification file
 * <tt>O:/Studium/PTC/Workspace/Nase/src/ptc/nase/frontend/JFlexNaseScanner.lex</tt>
 */
public final class JFlexNaseScanner implements IScanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\35\1\34\2\0\1\33\22\0\1\35\4\0\1\21\2\0"+
    "\1\24\1\25\1\17\1\16\1\12\1\15\1\0\1\20\12\37\1\13"+
    "\1\1\1\30\1\14\1\31\1\27\1\0\1\23\1\2\1\36\1\7"+
    "\1\3\1\26\1\4\1\36\1\5\4\36\1\6\1\22\2\36\1\11"+
    "\1\36\1\10\2\36\1\32\3\36\6\0\32\36\uff85\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\5\3\1\4\1\5\1\6\1\7"+
    "\1\10\1\11\1\12\1\13\2\3\1\14\1\15\1\3"+
    "\1\16\1\17\1\20\1\3\2\1\5\3\1\21\1\22"+
    "\2\3\1\23\1\24\2\3\1\25\1\26\2\3\1\27"+
    "\1\30\3\3\1\31\1\3\1\32\1\3\1\33\1\3"+
    "\1\34";

  private static int [] zzUnpackAction() {
    int [] result = new int[56];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\40\0\40\0\100\0\140\0\200\0\240\0\300"+
    "\0\40\0\340\0\40\0\40\0\40\0\40\0\40\0\40"+
    "\0\u0100\0\u0120\0\40\0\40\0\u0140\0\40\0\u0160\0\u0180"+
    "\0\u01a0\0\u01c0\0\u01e0\0\u0200\0\u0220\0\u0240\0\u0260\0\u0280"+
    "\0\40\0\200\0\u02a0\0\u02c0\0\40\0\40\0\u02e0\0\u0300"+
    "\0\200\0\200\0\u0320\0\u0340\0\200\0\200\0\u0360\0\u0380"+
    "\0\u03a0\0\200\0\u03c0\0\200\0\u03e0\0\200\0\u0400\0\200";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[56];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\3\6\1\10"+
    "\1\11\1\12\1\13\1\14\1\15\1\16\1\17\1\20"+
    "\1\21\1\22\1\23\1\24\1\25\1\26\1\27\1\30"+
    "\1\31\1\32\1\2\1\33\1\6\1\2\42\0\1\6"+
    "\1\34\6\6\10\0\2\6\2\0\1\6\3\0\1\6"+
    "\3\0\2\6\2\0\4\6\1\35\3\6\10\0\2\6"+
    "\2\0\1\6\3\0\1\6\3\0\2\6\2\0\10\6"+
    "\10\0\2\6\2\0\1\6\3\0\1\6\3\0\2\6"+
    "\2\0\3\6\1\36\1\37\3\6\10\0\2\6\2\0"+
    "\1\6\3\0\1\6\3\0\2\6\2\0\1\6\1\40"+
    "\6\6\10\0\2\6\2\0\1\6\3\0\1\6\3\0"+
    "\2\6\14\0\1\41\25\0\7\6\1\42\10\0\2\6"+
    "\2\0\1\6\3\0\1\6\3\0\2\6\2\0\4\6"+
    "\1\43\3\6\10\0\2\6\2\0\1\6\3\0\1\6"+
    "\3\0\2\6\2\0\3\6\1\44\4\6\10\0\2\6"+
    "\2\0\1\6\3\0\1\6\3\0\2\6\14\0\1\45"+
    "\37\0\1\46\25\0\7\6\1\47\10\0\2\6\2\0"+
    "\1\6\3\0\1\6\3\0\2\6\34\0\1\2\40\0"+
    "\1\33\4\0\2\6\1\50\5\6\10\0\2\6\2\0"+
    "\1\6\3\0\1\6\3\0\2\6\2\0\5\6\1\51"+
    "\2\6\10\0\2\6\2\0\1\6\3\0\1\6\3\0"+
    "\2\6\2\0\10\6\10\0\2\6\2\0\1\52\3\0"+
    "\1\6\3\0\2\6\2\0\6\6\1\53\1\6\10\0"+
    "\2\6\2\0\1\6\3\0\1\6\3\0\2\6\2\0"+
    "\10\6\10\0\1\6\1\54\2\0\1\6\3\0\1\6"+
    "\3\0\2\6\2\0\5\6\1\55\2\6\10\0\2\6"+
    "\2\0\1\6\3\0\1\6\3\0\2\6\2\0\3\6"+
    "\1\56\4\6\10\0\2\6\2\0\1\6\3\0\1\6"+
    "\3\0\2\6\2\0\3\6\1\57\4\6\10\0\2\6"+
    "\2\0\1\6\3\0\1\6\3\0\2\6\2\0\3\6"+
    "\1\60\4\6\10\0\2\6\2\0\1\6\3\0\1\6"+
    "\3\0\2\6\2\0\1\6\1\61\6\6\10\0\2\6"+
    "\2\0\1\6\3\0\1\6\3\0\2\6\2\0\5\6"+
    "\1\62\2\6\10\0\2\6\2\0\1\6\3\0\1\6"+
    "\3\0\2\6\2\0\6\6\1\63\1\6\10\0\2\6"+
    "\2\0\1\6\3\0\1\6\3\0\2\6\2\0\4\6"+
    "\1\64\3\6\10\0\2\6\2\0\1\6\3\0\1\6"+
    "\3\0\2\6\2\0\2\6\1\65\5\6\10\0\2\6"+
    "\2\0\1\6\3\0\1\6\3\0\2\6\2\0\1\6"+
    "\1\66\6\6\10\0\2\6\2\0\1\6\3\0\1\6"+
    "\3\0\2\6\2\0\1\6\1\67\6\6\10\0\2\6"+
    "\2\0\1\6\3\0\1\6\3\0\2\6\2\0\7\6"+
    "\1\70\10\0\2\6\2\0\1\6\3\0\1\6\3\0"+
    "\2\6";

  private static int [] zzUnpackTrans() {
    int [] result = new int[1056];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\2\11\5\1\1\11\1\1\6\11\2\1\2\11"+
    "\1\1\1\11\12\1\1\11\3\1\2\11\22\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[56];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */

	public JFlexNaseScanner(String filename) throws FileNotFoundException
	{
		this(new FileReader(filename + Nase.IN_FILE_EXTENSION));
		Listing.init(filename);
	}

	private SymbolTable symbolTable;
	private int currentSymbol;

	public long getCurrentLine()
	{
		return yycolumn + 1;
	}
	
	public long getCurrentColumn()
	{
		return yyline + 1;
	}
	
	public SymbolTable getSymbolTable()
	{
		return symbolTable;
	}
	
	public boolean getNextSymbol() throws IOException
	{
		currentSymbol = yylex();
			
		return true;
	}
	
	public void skipToDelimiter()
	{
		//TODO
		System.out.println("TODO: skipToDelimiter");
	}
	
	public int getCurrentSymbol()
	{
		return currentSymbol;
	}



  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public JFlexNaseScanner(java.io.Reader in) {
  		symbolTable = new SymbolTable();
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public JFlexNaseScanner(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 96) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public int yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 22: 
          { return SymbolTable.ST_INLINE_IF_SYMBOL;
          }
        case 29: break;
        case 28: 
          { return SymbolTable.ST_INT_TYPE_SYMBOL;
          }
        case 30: break;
        case 27: 
          { return SymbolTable.ST_WRITE_SYMBOL;
          }
        case 31: break;
        case 25: 
          { return SymbolTable.ST_READ_SYMBOL;
          }
        case 32: break;
        case 21: 
          { return SymbolTable.ST_END_SYMBOL;
          }
        case 33: break;
        case 16: 
          { return SymbolTable.ST_GT_SYMBOL;
          }
        case 34: break;
        case 15: 
          { return SymbolTable.ST_LT_SYMBOL;
          }
        case 35: break;
        case 3: 
          { int symbol = symbolTable.classifySymbol(yytext());
								if (symbol == SymbolTable.ST_NULL_SYMBOL)
								{
									symbol = symbolTable.insertUserSymbol(yytext());
								}
								
								return symbol;
          }
        case 36: break;
        case 23: 
          { return SymbolTable.ST_AND_SYMBOL;
          }
        case 37: break;
        case 9: 
          { return SymbolTable.ST_TIMES_SYMBOL;
          }
        case 38: break;
        case 14: 
          { return SymbolTable.ST_INLINE_THEN_SYMBOL;
          }
        case 39: break;
        case 10: 
          { return SymbolTable.ST_DIVIDE_SYMBOL;
          }
        case 40: break;
        case 8: 
          { return SymbolTable.ST_PLUS_SYMBOL;
          }
        case 41: break;
        case 19: 
          { return SymbolTable.ST_LE_SYMBOL;
          }
        case 42: break;
        case 4: 
          { return SymbolTable.ST_COMMA_SYMBOL;
          }
        case 43: break;
        case 5: 
          { return SymbolTable.ST_INLINE_ELSE_SYMBOL;
          }
        case 44: break;
        case 26: 
          { return SymbolTable.ST_BEGIN_SYMBOL;
          }
        case 45: break;
        case 2: 
          { return SymbolTable.ST_DELIMITER_SYMBOL;
          }
        case 46: break;
        case 24: 
          { return SymbolTable.ST_INLINE_FI_SYMBOL;
          }
        case 47: break;
        case 11: 
          { return SymbolTable.ST_MODULO_SYMBOL;
          }
        case 48: break;
        case 17: 
          { return SymbolTable.ST_ASSIGN_SYMBOL;
          }
        case 49: break;
        case 7: 
          { return SymbolTable.ST_MINUS_SYMBOL;
          }
        case 50: break;
        case 6: 
          { return SymbolTable.ST_EQ_SYMBOL;
          }
        case 51: break;
        case 20: 
          { return SymbolTable.ST_GE_SYMBOL;
          }
        case 52: break;
        case 13: 
          { return SymbolTable.ST_CLOSE_PARENTHESIS_SYMBOL;
          }
        case 53: break;
        case 18: 
          { return SymbolTable.ST_OR_SYMBOL;
          }
        case 54: break;
        case 1: 
          { 
          }
        case 55: break;
        case 12: 
          { return SymbolTable.ST_OPEN_PARENTHESIS_SYMBOL;
          }
        case 56: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
              { 		return SymbolTable.ST_EOF_SYMBOL;
 }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
