package symboltable;

public enum Symbols {
	NULL_SYMBOL, EOF_SYMBOL, DELIMITER_SYMBOL, BEGIN_SYMBOL,
	END_SYMBOL, INT_TYPE_SYMBOL, COMMA_SYMBOL, ASSIGN_SYMBOL,
	MINUS_SYMBOL, PLUS_SYMBOL, TIMES_SYMBOL, DIVIDE_SYMBOL,
	MODULO_SYMBOL, OR_SYMBOL, AND_SYMBOL, OPEN_PARAENTHESIS_SYMBOL,
	CLOSE_PARENTHESIS_SYMBOL, INLINE_IF_SYMBOL, INLINE_FI_SYMBOL, INLINE_THEN_SYMBOL,
	INLINE_ELSE_SYMBOL, LT_SYMBOL, LE_SYMBOL, EQ_SYMBOL, GE_SYMBOL,
	GT_SYMBOL, NE_SYMBOL, READ_SYMBOL, WRITE_SYMBOL
}
